spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
<<<<<<< HEAD
spring.jpa.show-sql=true 
jwt.secret=TumchaKhupMothaAniSecureSecretKeyItheTaka12345678901234567890
jwt.expirationMs=86400000
=======
spring.jpa.show-sql=true
>>>>>>> e246e3a2d95044c5c0108f0aab786541cdacdb24
